// Faction emblem — generated by scripts/fetch-art.ts via pollinations.ai
// and committed to public/art/factions/. Falls back to a styled letter tile
// when the file is missing (mid-fetch, broken path, etc).

import { useState } from 'react';
import type { FactionId } from '@engine/types';

const FACTION_LABELS: Record<FactionId, string> = {
  warriors: 'Warriors',
  assassins: 'Assassins',
  mages: 'Mages',
  necromancers: 'Necromancers',
  merchants: 'Merchants',
  rangers: 'Rangers',
  paladins: 'Paladins',
  beastmasters: 'Beastmasters',
};

export function FactionEmblem({
  factionId,
  size = 32,
  className = '',
}: {
  factionId: FactionId;
  size?: number;
  className?: string;
}) {
  const [failed, setFailed] = useState(false);
  const label = FACTION_LABELS[factionId];

  if (failed) {
    return (
      <div
        className={`inline-flex items-center justify-center rounded bg-neutral-800 text-xs font-semibold text-neutral-200 ${className}`}
        style={{ width: size, height: size }}
        title={label}
      >
        {label.slice(0, 2)}
      </div>
    );
  }

  return (
    <img
      src={`/art/factions/${factionId}.jpg`}
      alt={`${label} emblem`}
      width={size}
      height={size}
      onError={() => setFailed(true)}
      className={`inline-block rounded object-cover ${className}`}
      style={{ width: size, height: size }}
    />
  );
}

export function factionLabel(id: FactionId): string {
  return FACTION_LABELS[id];
}
